spring.application.name=${SPRING_APPLICATION_NAME}

# Frontend config
frontend.url=${FRONTEND_URL}

# basic authentication - not require since jwt is already in place
spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

#database config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#hibernate config - update policy and MySQL-compatible SQL statements
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

# jwt config
spring.app.jwtSecret=${SPRING_APP_JWT_SECRET}
spring.app.jwtExpirationMs=${SPRING_APP_JWT_EXPIRATION_MS}

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SMS config
twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.verification.service.sid=${TWILIO_VERIFY_SERVICE_SID}
twilio.default.country.code=91

#logging level config
logging.level.root=INFO
logging.level.com.secure.apnastaybackend=INFO
logging.level.org.springframework.security=INFO
#logging.level.org.hibernate.SQL=INFO
#logging.level.org.springframework.jdbc.core=INFO
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Google OAuth2 configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
